### ISSUE TITLE
Visibility issues with style.drag_overlay value

### ISSUE THREAD

**Issue by kmandarin-orange** [juliardi/lite-xl-ayu-theme#1]
Hi, found this theme from your issue on the lite-xl-colors repo and gave it a spin. Great port of ayu, I had just noticed that there's visibility issues with dragging and dropping tabs to tile/side-by-side different documents. The transparent overlay showing how the tab will tile is really hard to see, would it make sense to change the value to something more visible, maybe even simply use the text selection or the scrollbar style? It's just very hard to see a white overlay over a white background and bright text.

**Comment by juliardi** [comment]
Hi, thanks for using this theme. I have just updated the drag_overlay color for ayu-light. Please try it and see if it is better than before.

https://user-images.githubusercontent.com/4223302/229402224-607775a9-f4ff-44b3-a4b5-1adf04613f24.mp4

**Comment by kmandarin-orange** [comment]
Looks great to me, thanks for such a fast response. This solves the problem perfectly, so I'll go ahead and close this issue 👍
